import { useMemo, useRef, useState } from 'react';
import { CalendarDays, ChartNoAxesColumnIncreasing, ChevronDown, ChevronLeft, ChevronRight, Clock3, CloudSun, Download, Heart, Home, Leaf, Menu, MoonStar, Palette, Pencil, Plus, Search, Settings, Share2, Sparkles, Star, Sun, Trash2, Upload, X } from 'lucide-react';
import { allEmotions, emotionFamilies, getEmotion, getState, relationIds, states } from './data';
import { useJournal } from './context';
import { averageIntensity, dateFromKey, entriesCount, formatFullDate, formatMonth, frequency, hslToHex, localDateKey, timeGroup, timeValue, uid } from './utils';
import { journalStorage, validateBackup } from './storage';
import type { BackupFile, DayData, EmotionNode, Intensity, JournalEntry, SelectedEmotion, SelectedState, StateItem } from './types';

type Page='today'|'calendar'|'emotions'|'stats'|'settings';
const pageTitles:Record<Page,string>={today:'Сегодня',calendar:'Календарь',emotions:'Эмоции',stats:'Статистика',settings:'Настройки'};
const navItems:[Page,string,typeof Home][]=[['today','Сегодня',Home],['calendar','Календарь',CalendarDays],['emotions','Эмоции',Heart],['stats','Статистика',ChartNoAxesColumnIncreasing],['settings','Настройки',Settings]];
const intensityLabels=['','едва заметно','слабое','заметное','сильное','очень сильное'];

function IconButton({label,children,onClick,className=''}:{label:string;children:React.ReactNode;onClick?:()=>void;className?:string}){return <button type="button" className={`icon-button ${className}`} aria-label={label} title={label} onClick={onClick}>{children}</button>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={`sheet ${wide?'sheet-wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="sheet-handle"/><header className="sheet-header"><h2>{title}</h2><IconButton label="Закрыть" onClick={onClose}><X/></IconButton></header>{children}</section></div>}
function EmptyState({icon,children}:{icon:React.ReactNode;children:React.ReactNode}){return <div className="empty-state"><span>{icon}</span><p>{children}</p></div>}
function IntensityPicker({value,onChange}:{value?:Intensity;onChange:(x?:Intensity)=>void}){return <div className="intensity"><div className="intensity-dots" role="group" aria-label="Интенсивность">{([1,2,3,4,5] as Intensity[]).map(i=><button type="button" key={i} className={value&&i<=value?'active':''} aria-label={`${i}: ${intensityLabels[i]}`} onClick={()=>onChange(value===i?undefined:i)}/>)}</div><small>{value?`${value}/5 · ${intensityLabels[value]}`:'Можно не указывать'}</small></div>}

export default function App(){
  const [page,setPage]=useState<Page>('today');
  const [selectedDate,setSelectedDate]=useState(localDateKey());
  const [entryOpen,setEntryOpen]=useState(false);
  const [editing,setEditing]=useState<JournalEntry|undefined>();
  const [colorOpen,setColorOpen]=useState(false);
  const {loading}=useJournal();
  const openEntry=(entry?:JournalEntry,date=selectedDate)=>{setSelectedDate(date);setEditing(entry);setEntryOpen(true)};
  if(loading)return <div className="loading"><Leaf/><span>Открываем дневник…</span></div>;
  return <div className="app-shell">
    <aside className="side-nav"><div className="brand"><span className="brand-mark"><img src={`${import.meta.env.BASE_URL}icon-192.png`} alt=""/></span><div><b>Тихий день</b><small>дневник чувств</small></div></div><nav>{navItems.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><span>{label}</span></button>)}</nav><p className="privacy-mini"><MoonStar/> Только на твоём устройстве</p></aside>
    <main><div className="mobile-brand"><div className="brand"><span className="brand-mark"><img src={`${import.meta.env.BASE_URL}icon-192.png`} alt=""/></span><b>Тихий день</b></div><IconButton label="Настройки" onClick={()=>setPage('settings')}><Menu/></IconButton></div>
      {page==='today'&&<TodayPage onEntry={openEntry} onColor={(date)=>{setSelectedDate(date);setColorOpen(true)}}/>}
      {page==='calendar'&&<CalendarPage onEntry={openEntry} onColor={(date)=>{setSelectedDate(date);setColorOpen(true)}}/>}
      {page==='emotions'&&<EmotionsPage/>}
      {page==='stats'&&<StatsPage/>}
      {page==='settings'&&<SettingsPage/>}
    </main>
    <nav className="bottom-nav" aria-label="Основная навигация">{navItems.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined} onClick={()=>setPage(id)}><Icon/><span>{label}</span></button>)}</nav>
    {entryOpen&&<EntryEditor date={selectedDate} entry={editing} onClose={()=>setEntryOpen(false)}/>}
    {colorOpen&&<ColorPicker date={selectedDate} onClose={()=>setColorOpen(false)}/>}
  </div>
}

function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:React.ReactNode}){return <header className="page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>}

function TodayPage({onEntry,onColor}:{onEntry:(e?:JournalEntry,d?:string)=>void;onColor:(d:string)=>void}){
  const {days,saveDay}=useJournal(); const date=localDateKey(); const day=days.find(d=>d.date===date);
  const top=frequency(day?[day]:[],'emotions').slice(0,3);
  const remove=async(entry:JournalEntry)=>{if(!day||!confirm('Удалить эту отметку?'))return;await saveDay({...day,entries:day.entries.filter(e=>e.id!==entry.id),updatedAt:new Date().toISOString()})};
  return <div className="page today-page"><PageHeader eyebrow="Личный дневник" title={capitalize(formatFullDate(date))} description="Можно просто заметить, как тебе сейчас." action={<CloudSun className="header-illustration"/>}/>
    <section className="day-color-card card" style={day?.color?{'--day-color':day.color.hex} as React.CSSProperties:undefined}>
      <div className="card-label"><Palette/> Цвет моего дня</div>{day?.color?<><button className="color-display" onClick={()=>onColor(date)} aria-label="Изменить цвет дня"><span className="color-glow"/><strong>{day.color.label||'Сегодня этот оттенок'}</strong><small>{day.color.hex.toUpperCase()} · изменить</small></button></>:<button className="color-empty" onClick={()=>onColor(date)}><span className="paint-spot"><Sparkles/></span><span><b>Выбрать цвет дня</b><small>Любой оттенок — без готовых значений</small></span><ChevronRight/></button>}
    </section>
    <button className="primary-cta" onClick={()=>onEntry(undefined,date)}><span><Plus/></span>Отметить, что я чувствую</button>
    <section className="timeline-section"><div className="section-heading"><div><span className="eyebrow">Мой день</span><h2>Отметки по времени</h2></div>{day?.entries.length?<span className="count-badge">{day.entries.length}</span>:null}</div>
      {!day?.entries.length?<EmptyState icon={<Leaf/>}>Здесь появятся твои отметки за день.<button className="text-button" onClick={()=>onEntry(undefined,date)}>Отметить первое чувство</button></EmptyState>:<div className="timeline">{[...day.entries].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).map(e=><EntryCard key={e.id} entry={e} onEdit={()=>onEntry(e,date)} onDelete={()=>remove(e)}/>)}</div>}
    </section>
    {day?.entries.length?<section className="summary-card card"><span className="eyebrow">Без оценок — только наблюдение</span><h3>Сегодня {plural(day.entries.length,'отметка','отметки','отметок')}</h3>{top.length>0&&<><p>Чаще отмечались:</p><div className="summary-chips">{top.map(([id])=><span key={id}>{getEmotion(id)?.node.label||id}</span>)}</div></>}</section>:null}
  </div>
}

function EntryCard({entry,onEdit,onDelete}:{entry:JournalEntry;onEdit:()=>void;onDelete:()=>void}){const {settings}=useJournal();return <article className="entry-card"><div className="timeline-time"><Clock3/><time>{timeValue(entry.timestamp)}</time></div><div className="entry-content"><div className="entry-top"><div className="emotion-list">{entry.emotions.map(x=><span key={x.emotionId} className="emotion-pill" style={{'--pill':emotionFamilies.find(f=>f.id===x.familyId)?.accent} as React.CSSProperties}>{emotionName(x.emotionId,settings)}{x.intensity&&<small>{x.intensity}/5</small>}</span>)}</div><div className="entry-actions"><IconButton label="Редактировать" onClick={onEdit}><Pencil/></IconButton><IconButton label="Удалить" onClick={onDelete}><Trash2/></IconButton></div></div>{entry.states.length>0&&<div className="state-line">{entry.states.map(x=><span key={x.stateId}>{stateName(x.stateId,settings)}{x.intensity?` · ${x.intensity}/5`:''}</span>)}</div>}{entry.note&&<p className="entry-note">{entry.note}</p>}</div></article>}

function EntryEditor({date,entry,onClose}:{date:string;entry?:JournalEntry;onClose:()=>void}){
  const {days,settings,saveDay,saveSettings}=useJournal();
  const [step,setStep]=useState(1); const [selected,setSelected]=useState<SelectedEmotion[]>(entry?.emotions??[]);const [selectedStates,setSelectedStates]=useState<SelectedState[]>(entry?.states??[]);const [note,setNote]=useState(entry?.note??'');
  const initial=entry?`${String(new Date(entry.timestamp).getHours()).padStart(2,'0')}:${String(new Date(entry.timestamp).getMinutes()).padStart(2,'0')}`:new Date().toTimeString().slice(0,5);const [time,setTime]=useState(initial);const [families,setFamilies]=useState<string[]>([...new Set(entry?.emotions.map(e=>e.familyId)??[])]);const [query,setQuery]=useState('');
  const toggle=(id:string,familyId:string)=>setSelected(old=>old.some(x=>x.emotionId===id)?old.filter(x=>x.emotionId!==id):[...old,{emotionId:id,familyId}]);
  const toggleState=(id:string)=>setSelectedStates(old=>old.some(x=>x.stateId===id)?old.filter(x=>x.stateId!==id):[...old,{stateId:id}]);
  const save=async()=>{const now=new Date();const base=dateFromKey(date);const [h,m]=time.split(':').map(Number);base.setHours(h,m,0,0);const item:JournalEntry={id:entry?.id??uid(),timestamp:base.toISOString(),emotions:selected,states:selectedStates,note:note.trim()||undefined,createdAt:entry?.createdAt??now.toISOString(),updatedAt:now.toISOString()};const current=days.find(d=>d.date===date);const next:DayData=current?{...current,entries:[...current.entries.filter(e=>e.id!==item.id),item],updatedAt:now.toISOString()}:{date,entries:[item],createdAt:now.toISOString(),updatedAt:now.toISOString()};await saveDay(next);const recent=[...selected.map(x=>x.emotionId),...settings.recentEmotions].filter((v,i,a)=>a.indexOf(v)===i).slice(0,8);await saveSettings({...settings,recentEmotions:recent});onClose()};
  return <Modal title={entry?'Редактировать отметку':'Новая отметка'} onClose={onClose} wide><div className="stepper" aria-label={`Шаг ${step} из 4`}>{[1,2,3,4].map(i=><span key={i} className={i<=step?'active':''}/>)}</div>
    <div className="sheet-body entry-editor">
      {step===1&&<><div className="question"><span>1 · Эмоции</span><h3>Что сейчас ближе всего?</h3><p>Можно выбрать несколько и остановиться на любом уровне.</p></div>{settings.recentEmotions.length>0&&<PickerRow title="Недавно" ids={settings.recentEmotions} selected={selected} onToggle={toggle} custom={settings.customEmotions}/>} {settings.favoriteEmotions.length>0&&<PickerRow title="Избранное" ids={settings.favoriteEmotions} selected={selected} onToggle={toggle} custom={settings.customEmotions}/>} {settings.customEmotions.length>0&&<div className="quick-row"><div className="mini-heading"><Heart/> Мои слова</div><div>{settings.customEmotions.map(x=><button key={x.id} className={selected.some(s=>s.emotionId===x.id)?'active':''} onClick={()=>toggle(x.id,x.familyId)}>{x.label}</button>)}</div></div>}<button className="unsure-button" onClick={()=>setStep(5)}><Sparkles/><span><b>Не могу понять, что я чувствую</b><small>Небольшая спокойная подсказка</small></span><ChevronRight/></button><div className="family-grid">{emotionFamilies.map(f=><button key={f.id} className={families.includes(f.id)?'selected':''} style={{'--family':f.accent} as React.CSSProperties} onClick={()=>setFamilies(x=>x.includes(f.id)?x.filter(v=>v!==f.id):[...x,f.id])}><span/><b>{f.label}</b><small>{f.children?.length} оттенков</small></button>)}</div>{families.length>0&&<div className="family-emotions">{families.map(id=><EmotionBranch key={id} family={emotionFamilies.find(f=>f.id===id)!} selected={selected} onToggle={toggle}/>)}</div>}<label className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти чувство"/></label>{query&&<div className="search-results">{[...allEmotions.map(x=>({id:x.node.id,label:x.node.label,familyId:x.familyId})),...settings.customEmotions].filter(x=>x.label.toLowerCase().includes(query.toLowerCase())).slice(0,12).map(x=><button key={`${x.familyId}-${x.id}`} className={selected.some(s=>s.emotionId===x.id)?'active':''} onClick={()=>toggle(x.id,x.familyId)}>{x.label}<small>{emotionFamilies.find(f=>f.id===x.familyId)?.label}</small></button>)}</div>}</>}
      {step===2&&<><div className="question"><span>2 · Интенсивность</span><h3>Насколько это ощущается?</h3><p>Если хочется, отметь силу каждого чувства.</p></div>{selected.length===0?<EmptyState icon={<Heart/>}>Ты можешь вернуться и выбрать чувства — или продолжить без них.</EmptyState>:<div className="intensity-list">{selected.map(x=><div key={x.emotionId}><b>{emotionName(x.emotionId,settings)}</b><IntensityPicker value={x.intensity} onChange={value=>setSelected(v=>v.map(e=>e.emotionId===x.emotionId?{...e,intensity:value}:e))}/></div>)}</div>}</>}
      {step===3&&<><div className="question"><span>3 · Состояние</span><h3>А как ты себя чувствуешь в целом?</h3><p>Это отдельно от эмоций. Можно выбрать несколько.</p></div><div className="chip-grid">{[...states,...settings.customStates].filter(s=>!settings.hiddenStates.includes(s.id)).map(s=><button key={s.id} className={selectedStates.some(x=>x.stateId===s.id)?'active':''} onClick={()=>toggleState(s.id)}>{s.label}{settings.favoriteStates.includes(s.id)&&<Star/>}</button>)}</div>{selectedStates.length>0&&<div className="intensity-list compact">{selectedStates.map(x=><div key={x.stateId}><b>{getState(x.stateId,settings.customStates)?.label}</b><IntensityPicker value={x.intensity} onChange={value=>setSelectedStates(v=>v.map(e=>e.stateId===x.stateId?{...e,intensity:value}:e))}/></div>)}</div>}</>}
      {step===4&&<><div className="question"><span>4 · Детали</span><h3>Почти готово</h3><p>Заметка — только если хочется.</p></div><label className="field"><span>Время</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label className="field"><span>Заметка</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Хочешь что-то добавить?" rows={4}/></label><div className="selection-summary"><small>Выбрано</small><b>{selected.length?selected.map(x=>emotionName(x.emotionId,settings)).join(', '):'Без выбранных эмоций'}</b>{selectedStates.length>0&&<span>{selectedStates.map(x=>stateName(x.stateId,settings)).join(', ')}</span>}</div></>}
      {step===5&&<UnsureHelper onPick={(ids)=>{ids.forEach(([id,family])=>{if(!selected.some(x=>x.emotionId===id))toggle(id,family)});setStep(1)}}/>}
    </div><footer className="sheet-footer"><button className="secondary-button" onClick={()=>step===1?onClose():setStep(step===5?1:step-1)}>{step===1?'Отмена':'Назад'}</button>{step!==5&&(step<4?<button className="primary-button" onClick={()=>setStep(step+1)}>Дальше <ChevronRight/></button>:<button className="primary-button" onClick={save}>Сохранить отметку</button>)}</footer>
  </Modal>
}

function PickerRow({title,ids,selected,onToggle,custom=[]}:{title:string;ids:string[];selected:SelectedEmotion[];onToggle:(a:string,b:string)=>void;custom?:{id:string;label:string;familyId:string}[]}){return <div className="quick-row"><div className="mini-heading"><Star/> {title}</div><div>{ids.map(id=>{const x=getEmotion(id);const own=custom.find(c=>c.id===id);return x||own?<button key={id} className={selected.some(s=>s.emotionId===id)?'active':''} onClick={()=>onToggle(id,x?.familyId||own!.familyId)}>{x?.node.label||own!.label}</button>:null})}</div></div>}
function EmotionBranch({family,selected,onToggle}:{family:EmotionNode;selected:SelectedEmotion[];onToggle:(a:string,b:string)=>void}){const [open,setOpen]=useState(true);return <section className="emotion-branch"><button className="branch-title" onClick={()=>setOpen(!open)}><span className="family-dot" style={{background:emotionFamilies.find(f=>f.id===family.id)?.accent}}/>{family.label}<ChevronDown className={open?'open':''}/></button>{open&&<div className="emotion-options"><button className={selected.some(s=>s.emotionId===family.id)?'active':''} onClick={()=>onToggle(family.id,family.id)}>{family.label}<small>общее чувство</small></button>{family.children?.map(node=><EmotionNodeOption key={node.id} node={node} familyId={family.id} selected={selected} onToggle={onToggle}/>)}</div>}</section>}
function EmotionNodeOption({node,familyId,selected,onToggle,depth=0}:{node:EmotionNode;familyId:string;selected:SelectedEmotion[];onToggle:(a:string,b:string)=>void;depth?:number}){const [open,setOpen]=useState(false);return <div className="node-wrap" style={{'--depth':depth} as React.CSSProperties}><button className={selected.some(s=>s.emotionId===node.id)?'active':''} onClick={()=>onToggle(node.id,familyId)}>{node.label}</button>{node.children&&<button className="expand-node" aria-label={`Уточнить ${node.label}`} onClick={()=>setOpen(!open)}><ChevronDown className={open?'open':''}/></button>}{open&&<div className="children">{node.children?.map(c=><EmotionNodeOption key={c.id} node={c} familyId={familyId} selected={selected} onToggle={onToggle} depth={depth+1}/>)}</div>}</div>}
function UnsureHelper({onPick}:{onPick:(x:[string,string][])=>void}){const [tone,setTone]=useState('');const [energy,setEnergy]=useState('');const suggestions=useMemo(()=>{if(!tone||!energy)return[];if(tone==='pleasant')return energy==='low'?[['peace','calm'],['relief','joy']]:energy==='high'?[['uplift','joy'],['interest','joy']]:[['satisfaction','joy'],['calm','calm']];if(tone==='unpleasant')return energy==='low'?[['sadness','sadness'],['helplessness','sadness']]:energy==='high'?[['anxiety','fear'],['irritation','anger']]:[['uncertainty','fear'],['disappointment','sadness']];return [['confusion','fear'],['interest','joy'],['inner_tension','fear']];},[tone,energy]) as [string,string][];
  return <div className="helper"><div className="question"><span>Это не тест</span><h3>Давай начнём с самого простого</h3><p>Подсказки не определяют твоё состояние — они лишь помогают найти близкие слова.</p></div><fieldset><legend>Скорее приятно, неприятно или смешанно?</legend><div className="segmented">{[['pleasant','Приятно'],['unpleasant','Неприятно'],['mixed','Смешанно'],['unknown','Не понимаю']].map(x=><button type="button" className={tone===x[0]?'active':''} key={x[0]} onClick={()=>setTone(x[0])}>{x[1]}</button>)}</div></fieldset><fieldset><legend>Сколько сейчас энергии?</legend><div className="segmented">{[['low','Мало'],['middle','Средне'],['high','Много']].map(x=><button type="button" className={energy===x[0]?'active':''} key={x[0]} onClick={()=>setEnergy(x[0])}>{x[1]}</button>)}</div></fieldset>{suggestions.length>0&&<div className="suggestions"><span className="eyebrow">Возможно, тебе близко что-то из этого</span>{suggestions.map(([id,f])=><button key={id} onClick={()=>onPick([[id,f]])}>{getEmotion(id)?.node.label}<ChevronRight/></button>)}</div>}</div>}

function ColorPicker({date,onClose}:{date:string;onClose:()=>void}){const {days,saveDay}=useJournal();const day=days.find(d=>d.date===date);const [h,setH]=useState(day?.color?.hsl.h??205);const [s,setS]=useState(day?.color?.hsl.s??28);const [l,setL]=useState(day?.color?.hsl.l??56);const [label,setLabel]=useState(day?.color?.label??'');const hex=hslToHex(h,s,l);const save=async()=>{const now=new Date().toISOString();await saveDay(day?{...day,color:{hex,hsl:{h,s,l},label:label.trim()||undefined},updatedAt:now}:{date,color:{hex,hsl:{h,s,l},label:label.trim()||undefined},entries:[],createdAt:now,updatedAt:now});onClose()};return <Modal title="Цвет дня" onClose={onClose}><div className="sheet-body color-picker"><div className="question"><span>{formatFullDate(date)}</span><h3>Какого цвета этот день?</h3><p>Здесь нет правильных значений — выбери свой оттенок.</p></div><div className="saturation-field" style={{'--h':h,'--l':l} as React.CSSProperties} aria-label="Область выбора насыщенности"><button type="button" style={{left:`${s}%`,top:`${100-l}%`}} aria-label="Текущий оттенок"/></div><label className="slider hue"><span><b>Оттенок</b><small>{Math.round(h)}°</small></span><input type="range" min="0" max="360" value={h} onChange={e=>setH(+e.target.value)}/></label><label className="slider"><span><b>Насыщенность</b><small>{Math.round(s)}%</small></span><input style={{accentColor:hex}} type="range" min="0" max="100" value={s} onChange={e=>setS(+e.target.value)}/></label><label className="slider"><span><b>Светлота</b><small>{Math.round(l)}%</small></span><input style={{accentColor:hex}} type="range" min="12" max="92" value={l} onChange={e=>setL(+e.target.value)}/></label><div className="color-preview" style={{background:hex,color:l<48?'white':'#25342c'}}><small>Сегодня</small><strong>{label||'Мой собственный оттенок'}</strong><span>{hex.toUpperCase()}</span></div><label className="field"><span>Название цвета <small>необязательно</small></span><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Например, пыльная лаванда"/></label></div><footer className="sheet-footer"><button className="secondary-button" onClick={onClose}>Отмена</button><button className="primary-button" onClick={save}>Сохранить цвет</button></footer></Modal>}

function CalendarPage({onEntry,onColor}:{onEntry:(e?:JournalEntry,d?:string)=>void;onColor:(d:string)=>void}){const {days}=useJournal();const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});const [detail,setDetail]=useState<string>();const first=(month.getDay()+6)%7;const total=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const cells=Array.from({length:first+total},(_,i)=>i<first?null:i-first+1);const go=(n:number)=>setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));return <div className="page"><PageHeader eyebrow="Палитра времени" title="Календарь" description="Каждый сохранённый оттенок остаётся именно таким, как ты его выбрала."/><section className="calendar-card card"><div className="calendar-head"><IconButton label="Предыдущий месяц" onClick={()=>go(-1)}><ChevronLeft/></IconButton><h2>{capitalize(formatMonth(month))}</h2><IconButton label="Следующий месяц" onClick={()=>go(1)}><ChevronRight/></IconButton></div><div className="weekdays">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{cells.map((d,i)=>{if(!d)return <span key={`e${i}`}/>;const key=localDateKey(new Date(month.getFullYear(),month.getMonth(),d));const day=days.find(x=>x.date===key);return <button key={key} className={`${key===localDateKey()?'today':''} ${day?'has-data':''}`} onClick={()=>setDetail(key)} aria-label={`${d} ${formatMonth(month)}${day?.entries.length?`, записей: ${day.entries.length}`:''}`}><span>{d}</span>{day?.color?<i style={{background:day.color.hex}}/>:day?.entries.length?<i className="entry-dot"/>:null}</button>})}</div></section>{days.filter(d=>d.color&&d.date.startsWith(localDateKey(month).slice(0,7))).length?<section className="mosaic card"><div><span className="eyebrow">Сохранённые оттенки</span><h3>Палитра месяца</h3></div><div>{days.filter(d=>d.color&&d.date.startsWith(localDateKey(month).slice(0,7))).map(d=><button aria-label={formatFullDate(d.date)} title={d.color?.label||formatFullDate(d.date)} key={d.date} style={{background:d.color!.hex}} onClick={()=>setDetail(d.date)}/>)}</div></section>:<EmptyState icon={<Palette/>}>Пока здесь тихо. Со временем календарь наполнится твоими оттенками.</EmptyState>}{detail&&<DayDetails date={detail} onClose={()=>setDetail(undefined)} onEntry={(entry)=>{setDetail(undefined);onEntry(entry,detail)}} onColor={()=>{setDetail(undefined);onColor(detail)}}/>}</div>}
function DayDetails({date,onClose,onEntry,onColor}:{date:string;onClose:()=>void;onEntry:(entry?:JournalEntry)=>void;onColor:()=>void}){const {days,saveDay}=useJournal();const day=days.find(d=>d.date===date);const remove=async(e:JournalEntry)=>{if(!day||!confirm('Удалить эту отметку?'))return;await saveDay({...day,entries:day.entries.filter(x=>x.id!==e.id),updatedAt:new Date().toISOString()})};return <Modal title={capitalize(formatFullDate(date))} onClose={onClose}><div className="sheet-body day-details">{day?.color?<button className="detail-color" style={{background:day.color.hex,color:day.color.hsl.l<48?'white':'#25342c'}} onClick={onColor}><small>Цвет дня</small><b>{day.color.label||day.color.hex.toUpperCase()}</b><Pencil/></button>:<button className="dashed-button" onClick={onColor}><Palette/> Выбрать цвет этого дня</button>}<button className="primary-cta small" onClick={()=>onEntry()}><Plus/> Добавить отметку</button>{!day?.entries.length?<EmptyState icon={<Leaf/>}>В этот день пока нет отметок.</EmptyState>:<div className="timeline">{day.entries.map(e=><EntryCard key={e.id} entry={e} onEdit={()=>onEntry(e)} onDelete={()=>remove(e)}/>)}</div>}</div></Modal>}

function EmotionsPage(){const {settings,saveSettings}=useJournal();const [query,setQuery]=useState('');const [family,setFamily]=useState<string>();const [detail,setDetail]=useState<string>();const results=allEmotions.filter(x=>x.node.label.toLowerCase().includes(query.toLowerCase()));const favorite=async(id:string)=>saveSettings({...settings,favoriteEmotions:settings.favoriteEmotions.includes(id)?settings.favoriteEmotions.filter(x=>x!==id):[...settings.favoriteEmotions,id]});return <div className="page"><PageHeader eyebrow="Словарь ощущений" title="Исследовать эмоции" description="Не строгая классификация, а карта слов, которая помогает прислушаться к себе."/><label className="search-field large"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Например, «обид»"/><kbd>⌘ K</kbd></label>{query?<section className="reference-list"><div className="section-heading"><h2>Результаты</h2><span>{results.length}</span></div>{results.length?results.slice(0,30).map(({node,familyId})=><ReferenceRow key={`${familyId}-${node.id}`} node={node} familyId={familyId} favorite={settings.favoriteEmotions.includes(node.id)} onFavorite={()=>favorite(node.id)} onOpen={()=>setDetail(node.id)}/>):<EmptyState icon={<Search/>}>Такого слова пока нет. Попробуй часть слова.</EmptyState>}</section>:<><section><div className="section-heading"><div><span className="eyebrow">От общего к точному</span><h2>Семьи эмоций</h2></div></div><div className="reference-families">{emotionFamilies.map(f=><button key={f.id} style={{'--family':f.accent} as React.CSSProperties} onClick={()=>setFamily(f.id)}><span/><div><b>{f.label}</b><small>{f.children?.length} основных оттенков</small></div><ChevronRight/></button>)}</div></section>{settings.favoriteEmotions.length>0&&<section className="favorites-card card"><span className="eyebrow">Избранное</span><div>{settings.favoriteEmotions.map(id=><button key={id} onClick={()=>setDetail(id)}><Star/> {getEmotion(id)?.node.label}</button>)}</div></section>}</>}{family&&<FamilyReference familyId={family} onClose={()=>setFamily(undefined)} onDetail={setDetail} favorites={settings.favoriteEmotions} onFavorite={favorite}/>} {detail&&<EmotionDetails id={detail} onClose={()=>setDetail(undefined)}/>}</div>}
function ReferenceRow({node,familyId,favorite,onFavorite,onOpen}:{node:EmotionNode;familyId:string;favorite:boolean;onFavorite:()=>void;onOpen:()=>void}){return <article className="reference-row"><button className="reference-main" onClick={onOpen}><span className="family-dot" style={{background:emotionFamilies.find(f=>f.id===familyId)?.accent}}/><span><b>{node.label}</b><small>{emotionFamilies.find(f=>f.id===familyId)?.label}</small></span></button><IconButton label={favorite?'Убрать из избранного':'В избранное'} onClick={onFavorite} className={favorite?'favorite':''}><Star/></IconButton></article>}
function FamilyReference({familyId,onClose,onDetail,favorites,onFavorite}:{familyId:string;onClose:()=>void;onDetail:(x:string)=>void;favorites:string[];onFavorite:(x:string)=>void}){const f=emotionFamilies.find(x=>x.id===familyId)!;return <Modal title={f.label} onClose={onClose}><div className="sheet-body"><div className="family-banner" style={{'--family':f.accent} as React.CSSProperties}><span/><p>Можно выбрать широкое чувство или раскрыть более точные оттенки.</p></div><div className="reference-list">{[f,...(f.children||[])].map(n=><ReferenceRow key={n.id} node={n} familyId={f.id} favorite={favorites.includes(n.id)} onFavorite={()=>onFavorite(n.id)} onOpen={()=>onDetail(n.id)}/>)}</div></div></Modal>}
function EmotionDetails({id,onClose}:{id:string;onClose:()=>void}){const item=getEmotion(id);if(!item)return null;const related=relationIds[id]?.map(getEmotion).filter(Boolean)??[];return <Modal title={item.node.label} onClose={onClose}><div className="sheet-body emotion-detail"><span className="detail-family" style={{background:emotionFamilies.find(f=>f.id===item.familyId)?.accent}}>{emotionFamilies.find(f=>f.id===item.familyId)?.label}</span><p>{item.node.description||`Один из оттенков семьи «${emotionFamilies.find(f=>f.id===item.familyId)?.label}». Это слово можно использовать настолько широко или точно, насколько тебе подходит.`}</p>{item.node.children?.length&&<><h3>Более точные слова</h3><div className="detail-chips">{item.node.children.map(x=><span key={x.id}>{x.label}</span>)}</div></>}{related.length>0&&<><h3>Связанные слова</h3><div className="detail-chips">{related.map(x=><span key={x!.node.id}>{x!.node.label}</span>)}</div></>}</div></Modal>}

function StatsPage(){const {days,settings}=useJournal();const [period,setPeriod]=useState<7|30|0>(30);const filtered=useMemo(()=>period===0?days:days.filter(d=>d.date>=localDateKey(new Date(Date.now()-(period-1)*86400000))),[days,period]);const emotions=frequency(filtered,'emotions').slice(0,5),st=frequency(filtered,'states').slice(0,5);const groups=new Map<string,Map<string,number>>();filtered.forEach(d=>d.entries.forEach(e=>{const g=timeGroup(e.timestamp);if(!groups.has(g))groups.set(g,new Map());e.emotions.forEach(x=>groups.get(g)!.set(x.emotionId,(groups.get(g)!.get(x.emotionId)||0)+1))}));return <div className="page"><PageHeader eyebrow="Только из твоих отметок" title="Статистика" description="Спокойный взгляд на повторения — без оценок и толкований."/><div className="period-tabs">{([[7,'7 дней'],[30,'30 дней'],[0,'Всё время']] as const).map(([n,l])=><button key={n} className={period===n?'active':''} onClick={()=>setPeriod(n)}>{l}</button>)}</div>{entriesCount(filtered)===0?<EmptyState icon={<ChartNoAxesColumnIncreasing/>}>Нужно немного больше записей, чтобы появились закономерности.</EmptyState>:<><div className="stats-overview"><div className="stat-number card"><small>Отметок</small><strong>{entriesCount(filtered)}</strong><span>в выбранном периоде</span></div><div className="stat-number card"><small>Средняя интенсивность</small><strong>{averageIntensity(filtered)?averageIntensity(filtered).toFixed(1):'—'}</strong><span>{averageIntensity(filtered)?'из 5, где была указана':'пока не указана'}</span></div></div><div className="stats-grid"><RankCard title="Чаще отмечались эмоции" items={emotions.map(([id,n])=>[emotionName(id,settings),n])}/><RankCard title="Чаще отмечались состояния" items={st.map(([id,n])=>[stateName(id,settings),n])}/></div><section className="card time-stats"><span className="eyebrow">Время суток</span><h2>Когда что отмечалось</h2><div>{['Утро','День','Вечер','Ночь'].map(g=>{const top=[...(groups.get(g)||new Map())].sort((a,b)=>b[1]-a[1]).slice(0,3);return <article key={g}><b>{g}</b>{top.length?<p>{top.map(x=>emotionName(x[0],settings)).join(' · ')}</p>:<p className="muted">Пока нет отметок</p>}</article>})}</div></section>{filtered.some(d=>d.color)&&<section className="card color-history"><span className="eyebrow">Без трактовок</span><h2>История оттенков</h2><div>{filtered.filter(d=>d.color).map(d=><span key={d.date} style={{background:d.color!.hex}} title={`${formatFullDate(d.date)} — ${d.color!.label||d.color!.hex}`}/>)}</div></section>}</>}</div>}
function RankCard({title,items}:{title:string;items:[string,number][]}){const max=items[0]?.[1]||1;return <section className="rank-card card"><h2>{title}</h2>{items.length?items.map(([name,n],i)=><div className="rank-row" key={name}><span className="rank-index">{i+1}</span><div><p><b>{name}</b><span>{n}</span></p><i><em style={{width:`${n/max*100}%`}}/></i></div></div>):<p className="muted">Пока нет данных</p>}</section>}

function SettingsPage(){const {days,settings,saveSettings,refresh}=useJournal();const inputRef=useRef<HTMLInputElement>(null);const [notice,setNotice]=useState('');const [preview,setPreview]=useState<BackupFile>();const [customState,setCustomState]=useState('');const [customEmotion,setCustomEmotion]=useState('');const [customFamily,setCustomFamily]=useState('calm');
  const makeBackup=async(share=false)=>{const data=await journalStorage.exportAll();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const file=new File([blob],`feelings-journal-backup-${localDateKey()}.json`,{type:'application/json'});if(share&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Резервная копия «Тихий день»'});return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();URL.revokeObjectURL(a.href);setNotice('Резервная копия сохранена.');};
  const readFile=async(file?:File)=>{if(!file)return;try{setPreview(validateBackup(JSON.parse(await file.text())));setNotice('')}catch(e){setNotice(e instanceof Error?e.message:'Файл не удалось прочитать.')}};
  const importData=async(strategy:'merge'|'replace')=>{if(!preview)return;if(strategy==='replace'&&!confirm('Текущие данные будут заменены. Сначала рекомендуется сохранить резервную копию. Продолжить?'))return;await journalStorage.importAll(preview,strategy);await refresh();setPreview(undefined);setNotice(strategy==='merge'?'Данные аккуратно объединены.':'Данные заменены из резервной копии.')};
  const clear=async()=>{if(!confirm('Удалить все записи, цвета и настройки на этом устройстве? Это действие нельзя отменить.'))return;await journalStorage.clearAll();await refresh();setNotice('Все локальные данные удалены.')};
  const addState=async()=>{if(!customState.trim())return;const x:StateItem={id:`custom_state_${uid()}`,label:customState.trim(),custom:true};await saveSettings({...settings,customStates:[...settings.customStates,x]});setCustomState('')};
  const addEmotion=async()=>{if(!customEmotion.trim())return;await saveSettings({...settings,customEmotions:[...settings.customEmotions,{id:`custom_emotion_${uid()}`,label:customEmotion.trim(),familyId:customFamily}]});setCustomEmotion('')};
  return <div className="page settings-page"><PageHeader eyebrow="Всё под рукой" title="Настройки" description="Данные остаются у тебя. Здесь можно сохранить копию и настроить дневник."/>{notice&&<div className="notice" role="status"><Leaf/>{notice}<button aria-label="Закрыть" onClick={()=>setNotice('')}><X/></button></div>}<section className="settings-section card"><div className="settings-title"><span><Download/></span><div><h2>Данные</h2><p>Экспорт, перенос и восстановление</p></div></div><div className="data-actions"><button onClick={()=>makeBackup(false)}><Download/><span><b>Экспортировать данные</b><small>JSON · {plural(days.length,'день','дня','дней')}</small></span><ChevronRight/></button>{'share' in navigator&&<button onClick={()=>makeBackup(true)}><Share2/><span><b>Поделиться копией</b><small>Через системное меню</small></span><ChevronRight/></button>}<button onClick={()=>inputRef.current?.click()}><Upload/><span><b>Импортировать данные</b><small>Из резервной копии JSON</small></span><ChevronRight/></button><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={e=>readFile(e.target.files?.[0])}/></div><p className="privacy-note"><Leaf/> Все записи хранятся только на этом устройстве, пока ты сама не экспортируешь их.</p></section>
    {preview&&<section className="import-preview card"><span className="eyebrow">Файл проверен</span><h2>Найдено в копии</h2><div><p><strong>{preview.days.length}</strong><span>дней</span></p><p><strong>{preview.days.reduce((n,d)=>n+d.entries.length,0)}</strong><span>записей</span></p><p><strong>{preview.days.filter(d=>d.color).length}</strong><span>цветов дня</span></p></div><button className="primary-button" onClick={()=>importData('merge')}>Объединить с текущими</button><button className="secondary-button" onClick={()=>importData('replace')}>Заменить текущие данные</button></section>}
    <section className="settings-section card"><div className="settings-title"><span><Palette/></span><div><h2>Интерфейс</h2><p>Тема и движение</p></div></div><fieldset className="theme-control"><legend>Тема</legend>{([['light','Светлая',Sun],['dark','Тёмная',MoonStar],['system','Как в системе',Settings]] as const).map(([id,label,Icon])=><button type="button" key={id} className={settings.theme===id?'active':''} onClick={()=>saveSettings({...settings,theme:id})}><Icon/>{label}</button>)}</fieldset><label className="switch-row"><span><b>Меньше анимации</b><small>Убрать плавные появления</small></span><input type="checkbox" checked={settings.reduceMotion} onChange={e=>saveSettings({...settings,reduceMotion:e.target.checked})}/></label></section>
    <section className="settings-section card"><div className="settings-title"><span><Heart/></span><div><h2>Свои слова</h2><p>Добавь подходящие именно тебе</p></div></div><div className="custom-form"><label className="field"><span>Новое состояние</span><div><input value={customState} onChange={e=>setCustomState(e.target.value)} placeholder="Например, уютная бодрость"/><button onClick={addState} aria-label="Добавить состояние"><Plus/></button></div></label>{settings.customStates.length>0&&<div className="custom-list">{settings.customStates.map(s=><span key={s.id}>{s.label}<button aria-label={`Удалить ${s.label}`} onClick={()=>saveSettings({...settings,customStates:settings.customStates.filter(x=>x.id!==s.id)})}><X/></button></span>)}</div>}<label className="field"><span>Новое чувство</span><div><input value={customEmotion} onChange={e=>setCustomEmotion(e.target.value)} placeholder="Название"/><button onClick={addEmotion} aria-label="Добавить чувство"><Plus/></button></div></label><label className="field"><span>Семья чувства</span><select value={customFamily} onChange={e=>setCustomFamily(e.target.value)}>{emotionFamilies.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>{settings.customEmotions.length>0&&<div className="custom-list">{settings.customEmotions.map(s=><span key={s.id}>{s.label}<button aria-label={`Удалить ${s.label}`} onClick={()=>saveSettings({...settings,customEmotions:settings.customEmotions.filter(x=>x.id!==s.id)})}><X/></button></span>)}</div>}</div></section>
    <section className="danger-zone"><div><h2>Очистить всё</h2><p>Удалить записи, цвета и настройки с этого устройства.</p></div><button onClick={clear}><Trash2/> Очистить данные</button></section><p className="version">Тихий день · версия 1.0<br/>Личный дневник, не медицинский инструмент.</p>
  </div>}

const capitalize=(s:string)=>s.charAt(0).toUpperCase()+s.slice(1);
const emotionName=(id:string,settings:{customEmotions:{id:string;label:string}[]})=>getEmotion(id)?.node.label||settings.customEmotions.find(x=>x.id===id)?.label||id;
const stateName=(id:string,settings:{customStates:StateItem[]})=>getState(id,settings.customStates)?.label||id;
function plural(n:number,one:string,few:string,many:string){const m=n%100;if(m>=11&&m<=14)return `${n} ${many}`;const x=n%10;return `${n} ${x===1?one:x>=2&&x<=4?few:many}`}
